//Accounts - Loading Types
export const ACCOUNTS_RELOAD = 'ACCOUNTS_RELOAD';
export const ACCOUNTS_LOADING = 'ACCOUNTS_LOADING';
export const ACCOUNTS_LOADING_SUCCESS = 'ACCOUNTS_LOADING_SUCCESS';
export const ACCOUNTS_LOADING_FAILURE = 'ACCOUNTS_LOADING_FAILURE';

//Contracts - Loading Types
export const CONTRACTS_RELOAD = 'CONTRACTS_RELOAD';
export const CONTRACTS_LOADING = 'CONTRACTS_LOADING';
export const CONTRACTS_LOADING_SUCCESS = 'CONTRACTS_LOADING_SUCCESS';
export const CONTRACTS_LOADING_FAILURE = 'CONTRACTS_LOADING_FAILURE';

//Peers - Loading Types
export const PEERS_RELOAD = 'PEERS_RELOAD';
export const PEERS_LOADING = 'PEERS_LOADING';
export const PEERS_LOADING_SUCCESS = 'PEERS_LOADING_SUCCESS';
export const PEERS_LOADING_FAILURE = 'PEERS_LOADING_FAILURE';